inputs:
  - stdin:
      codec: json
      prometheus_counter:
        namespace: ""
        subsystem: ""
        name: "logfilter_stdin"
      add_fields:
        "[x1][x2]": 123
      threads: 3
      timestamp: timestamp
filters:
  - hello:
      echo: hello

outputs:
  - stdout:
      codec: json
      if:
        - EQ(message, "a")