inputs:
  - stdin:
      codec: json
      prometheus_counter:
        namespace: ""
        subsystem: ""
        name: "logfilter_stdin"
      add_fields:
        "[x1][x2]": [1,2,3]
      threads: 3
      timestamp: timestamp
filters:
  - hello:
      echo: ["echo", 9]

outputs:
  - stdout:
      codec: json
      if:
        - EQ(message, "a")